#ifndef MN42_BOARD_POWER_PROFILE_H
#define MN42_BOARD_POWER_PROFILE_H

#include <cstdint>

#ifndef POWER_CHOKED_V1
#define POWER_CHOKED_V1 1
#endif

#ifndef SPLIT_RAIL_REWORK
#define SPLIT_RAIL_REWORK 2
#endif

#ifndef MN42_BOARD_POWER_PROFILE
#define MN42_BOARD_POWER_PROFILE POWER_CHOKED_V1
#endif

#if MN42_BOARD_POWER_PROFILE == POWER_CHOKED_V1
#define MN42_BOARD_POWER_PROFILE_NAME "POWER_CHOKED_V1"
#define MN42_BOARD_POWER_PROFILE_RAIL_TOPOLOGY_VERIFIED false
#ifndef MN42_LED_BRIGHTNESS_CAP_VALUE
#define MN42_LED_BRIGHTNESS_CAP_VALUE 26
#endif
#ifndef MN42_SAFE_BENCH_LED_BRIGHTNESS_VALUE
#define MN42_SAFE_BENCH_LED_BRIGHTNESS_VALUE 26
#endif
#ifndef MN42_DEFAULT_LED_BRIGHTNESS_VALUE
#define MN42_DEFAULT_LED_BRIGHTNESS_VALUE 26
#endif
#ifndef MN42_DEMO_LED_BRIGHTNESS_VALUE
#define MN42_DEMO_LED_BRIGHTNESS_VALUE 26
#endif
#elif MN42_BOARD_POWER_PROFILE == SPLIT_RAIL_REWORK
#define MN42_BOARD_POWER_PROFILE_NAME "SPLIT_RAIL_REWORK"
#define MN42_BOARD_POWER_PROFILE_RAIL_TOPOLOGY_VERIFIED true
#ifndef MN42_LED_BRIGHTNESS_CAP_VALUE
#define MN42_LED_BRIGHTNESS_CAP_VALUE 255
#endif
#ifndef MN42_SAFE_BENCH_LED_BRIGHTNESS_VALUE
#define MN42_SAFE_BENCH_LED_BRIGHTNESS_VALUE 64
#endif
#ifndef MN42_DEFAULT_LED_BRIGHTNESS_VALUE
#define MN42_DEFAULT_LED_BRIGHTNESS_VALUE 48
#endif
#ifndef MN42_DEMO_LED_BRIGHTNESS_VALUE
#define MN42_DEMO_LED_BRIGHTNESS_VALUE 96
#endif
#else
#error "Unsupported MN42_BOARD_POWER_PROFILE. Use POWER_CHOKED_V1 or SPLIT_RAIL_REWORK."
#endif

namespace BoardPowerProfile {
inline constexpr char kName[] = MN42_BOARD_POWER_PROFILE_NAME;
inline constexpr uint8_t kLedBrightnessCap = MN42_LED_BRIGHTNESS_CAP_VALUE;
inline constexpr uint8_t kSafeBenchLedBrightness = MN42_SAFE_BENCH_LED_BRIGHTNESS_VALUE;
inline constexpr uint8_t kDefaultLedBrightness = MN42_DEFAULT_LED_BRIGHTNESS_VALUE;
inline constexpr uint8_t kDemoLedBrightness = MN42_DEMO_LED_BRIGHTNESS_VALUE;
inline constexpr bool kRailTopologyVerified = MN42_BOARD_POWER_PROFILE_RAIL_TOPOLOGY_VERIFIED;
} // namespace BoardPowerProfile

#endif // MN42_BOARD_POWER_PROFILE_H
