// Generated by tools/generate_contract_artifacts.py. Do not edit directly.
#ifndef MANIFEST_CONTRACT_H
#define MANIFEST_CONTRACT_H

#include <cstdint>

namespace ManifestContract {
inline constexpr char kDeviceName[] = "MOARkNOBS-42";
inline constexpr uint16_t kSchemaVersion = 9;
inline constexpr uint8_t kSlotCount = 42;
inline constexpr uint8_t kPotCount = 42;
inline constexpr uint8_t kEnvelopeCount = 6;
inline constexpr uint8_t kDefaultLedCount = 52;
inline constexpr char kDefaultPowerProfile[] = "POWER_CHOKED_V1";
inline constexpr uint8_t kDefaultLedBrightnessCap = 26;
inline constexpr bool kDefaultRailTopologyVerified = false;
} // namespace ManifestContract

#endif // MANIFEST_CONTRACT_H
