#include "unity_config.h" // bundles Arduino and corrals usbMIDI into our stub
#include <unity.h>

#include "Hardware/IO.h"

// Unity's Arduino harness insists on a sketch-style entry point.  This file is
// the conductor that runs every firmware unit test when you flash the
// teensy40_unity target.  Keep the RUN_TEST order roughly grouped so failures
// point you at the right subsystem.

void test_start_stop_cycle();
void test_pot_root_drives_default();
void test_note_dynamics_shape_arp_note_velocity_and_probability();
void test_slot_root_wins_over_pot();
void test_external_callback_sets_root();
void test_external_base_note_without_callback();
void test_external_missing_inputs_falls_back_to_pot();
void test_catches_up_when_ticks_pile_up();
void test_large_tick_backlog_is_bounded_and_not_replayed();
void test_random_shape_respects_jitter_depth();
void test_updown_shape_walks_full_range();
void test_drunk_shape_is_deterministic();
void test_drunk_shape_jitter_depth_expands_walk();
void test_euclidean_advances_pitch_by_hit_not_rest_position();
void test_swing_delays_offbeat_notes();
void test_stop_cancels_delayed_note_on();
void test_tempo_change_updates_tick_ms();
void test_profile_crc_rejects_corruption();
void test_profile_bounds_clamp();
void test_profile_round_trip_preserves_profile_payload();
void test_profile_v5_migration_preserves_state_and_defaults_pattern_length();
void test_config_load_prefers_primary_when_backup_copy_is_invalid();
void test_config_load_restores_from_backup_and_repairs_primary();
void test_config_load_restores_from_backup_when_primary_crc_is_invalid();
void test_config_load_resets_to_defaults_when_primary_and_backup_are_both_corrupt();
void test_profile_save_interruption_leaves_latest_copy_in_backup();
void test_lowpass_highpass_response();
void test_system_report();
void test_dispatch_handles_known_command();
void test_dispatch_handles_documented_query_commands();
void test_dispatch_set_led_clamps_without_persisting();
void test_dispatch_abort_set_all_clears_incomplete_upload();
void test_applied_checksum_covers_exported_filter_led_and_baseline_state();
void test_applied_checksum_covers_slot_arg_and_lfo_modulation();
void test_dispatch_handles_enter_config_mode_command();
void test_dispatch_handles_live_slot_injection_command();
void test_dispatch_handles_midi_test_command();
void test_dispatch_handles_live_note_dynamics_command_without_boot_request();
void test_dispatch_handles_live_arp_runtime_commands();
void test_dispatch_get_mod_matrix_reports_routes_and_conflicts();
void test_dispatch_get_mod_matrix_reports_lfo_route_truncation();
void test_dispatch_handles_profile_save_load_reset_commands();
void test_dispatch_reassembles_chunked_profile_patch();
void test_dispatch_active_profile_lfo_patch_applies_live();
void test_restore_active_profile_runtime_rehydrates_saved_modulation_snapshot();
void test_dispatch_set_arp_updates_live_state_without_persisting();
void test_dispatch_set_profile_arp_pattern_length_applies_and_persists();
void test_dispatch_set_clock_updates_live_state_without_persisting();
void test_dispatch_set_jitter_updates_live_state_without_persisting();
void test_dispatch_set_note_dynamics_updates_live_state_without_persisting();
void test_dispatch_inactive_profile_patch_merges_with_stored_profile_snapshot();
void test_dispatch_profile_patch_normalizes_route_scalars();
void test_dispatch_profile_patch_rejects_invalid_route_fields();
void test_dispatch_handles_macro_and_scene_snapshot_commands();
void test_dispatch_rejects_unknown_command();
void test_dispatch_set_all_reports_negative_contract_errors();
void test_display_init_failure_leaves_protocol_responsive();
void test_profile_storage_commands_restore_and_reset_live_state();
void test_macro_and_scene_storage_commands_report_inventory_and_restore_state();
void test_scoped_analog_provider_nesting();
void test_sequence_provider_cycles_values();
void test_set_provider_returns_previous();
void test_digital_provider_overrides_matrix_reads();
void test_parse_basic_sysex_template();
void test_parse_14bit_sysex_template();
void test_parse_rejects_bad_template();
void test_sysex_template_config_mutation_stays_valid();
void test_bulk_config_assembler_handles_chunks();
void test_bulk_config_assembler_waits_for_balanced_frame();
void test_bulk_config_assembler_resyncs_on_wrapper_start();
void test_bulk_config_assembler_detects_overflow();
void test_bulk_config_assembler_rejects_orphaned_fragment();
void test_bulk_config_assembler_updates_sequence_hint_after_restart();
void test_bulk_config_assembler_expires_abandoned_frame();
void test_format_ack_includes_checksum_and_seq();
void test_device_schema_advertises_runtime_controls();
void test_bulk_config_accepts_numeric_slot_type();
void test_bulk_config_accepts_wider_numeric_slot_type();
void test_bulk_config_accepts_integral_float_slot_type();
void test_bulk_config_accepts_type_name_alias();
void test_debounce_reports_state_change_after_stable_interval();
void test_debounce_restarts_timer_when_signal_bounces();
void test_exponential_moving_average_clamps_alpha_bounds();
void test_exponential_moving_average_rounds_weighted_result();
void test_arg_sanitize_clamps_sources();
void test_compute_slot_arg_level_blends_followers();
void test_legacy_arg_migration_populates_slots();
void test_led_animator_cycles_mode_order();
void test_led_animator_invalid_mode_falls_back_to_static();
void test_led_manager_clamps_brightness_to_board_power_profile();
void test_display_owner_od01_startup_dominates();
void test_display_owner_od02_config_modal_dominates_status();
void test_display_owner_od03_lfo_modal_dominates_status();
void test_display_owner_od04_jitter_modal_dominates_status();
void test_display_owner_od05_diagnostics_modal_dominates_status();
void test_display_owner_od06_status_dominates_non_modal();
void test_display_owner_od07_control_follows_status_timeout();
void test_display_owner_od08_screensaver_only_when_idle();
void test_diagnostic_record_persists_boot_and_apply_events();
void test_diagnostic_record_rejects_corrupt_storage();
void test_diagnostic_record_loop_overrun_only_grows();
void test_command_queue_preserves_existing_frame_on_overflow();
void test_command_queue_ingests_newline_terminated_input();
void test_command_queue_ignores_carriage_returns();
void test_command_queue_discards_overlong_input_until_newline();
void test_command_queue_initialize_clears_stale_dmame_state();
void test_command_queue_dequeue_sanitizes_invalid_dmame_state();
void test_scheduler_initializes_recurring_task_layout();
void test_runtime_pending_note_off_fires_when_due();
void test_runtime_pending_note_off_overflow_tracks_drop();
void test_runtime_note_admission_drops_note_when_release_queue_is_full();
void test_runtime_modulation_transport_budget_spreads_42_slot_burst();
void test_runtime_modulated_note_stress_preserves_note_off_capacity();
void test_runtime_sustained_cc_modulation_coalesces_and_remains_fair();
void test_runtime_mixed_modulation_admission_reaches_every_slot();
void test_runtime_failed_modulated_note_retries_after_release_capacity_returns();
void test_runtime_diagnostics_log_only_on_counter_changes();
void test_process_midi_polls_usb_clock_without_timer_isr_gate();
void test_internal_clock_ticks_continue_without_timeout_gap();
void test_internal_clock_catchup_is_phase_preserving_and_bounded();
void test_clocked_feed_emits_non_arp_slots_while_arp_runs();
void test_clocked_feed_ignores_unconfigured_default_slots();
void test_display_no_ack_suppresses_runtime_retry();
void test_webserial_state_snapshot_emits_expected_json();
void test_webserial_slot_patch_emits_schema_and_legacy_payloads();
void test_ui_update_note_dynamics_maps_control_pots();
void test_ui_update_arp_tuning_updates_length_and_shape();
void test_ui_update_arp_tuning_edit_mode_updates_gate_and_octave();
void test_ui_update_filter_tuning_persists_slot_payload();
void test_ui_filter_tuning_remote_payload_blocks_mismatched_control_pots();
void test_ui_filter_tuning_remote_payload_cancels_pending_local_persist();
void test_ui_stream_webserial_state_uses_active_slot_context();
void test_wait_guard_clamps_when_threshold_exceeds_wait();
void test_wait_guard_preserves_positive_delta();
void test_waveform_ranges();
void test_phase_continuity_free_run();
void test_sync_ticks_at_120_bpm();
void test_div_mult_math();
void test_sample_hold_length();
void test_golden_stats();
void test_lfo_clock_consumes_ticks();
void test_lfo_apply_profile_resets_sync_timing_baseline();
void test_lfo_slot_value_route_emits_slot_callback();
void test_lfo_slot_value_route_applies_signed_amount_and_range();
void test_slot_modulation_composes_ef_then_lfos();
void test_slot_modulation_supports_lfo_without_ef();
void test_slot_modulation_clamps_after_each_lane();
void test_slot_modulation_honors_ef_replace_before_lfo();
void test_slot_modulation_applies_replace_and_scale_lane_modes();
void test_slot_modulation_distinguishes_unipolar_add_from_centered();
void test_slot_modulation_centered_full_amount_spans_midi_range();
void test_slot_modulation_legacy_replace_preserves_output_curve();
void test_peak_mode_rises_and_falls();
void test_rms_mode_converges();
void test_gate_mode_hysteresis();
void test_idle_floor_suppresses_disconnected_float();
void test_auto_baseline_converges();
void test_auto_gain_targets_level();
void test_stats_report_mode_and_value();
void test_envelope_stats_sine_trace();
void test_envelope_stats_step_trace();
void test_envelope_stats_idle_noise();
void test_no_heap_growth_over_fake_runtime();
#if defined(UNIT_TEST) && defined(USB_MIDI_STUB)
void test_program_change();
void test_aftertouch();
void test_mod_wheel();
void test_pitch_bend();
void test_send_nrpn();
void test_receive_nrpn();
void test_parameter_decoders_are_isolated_per_channel();
void test_send_sysex();
void test_pot_burst_keeps_cc_counters_honest();
void test_oversized_sysex_is_rejected();
void test_drop_unsupported_usb_type();
void test_usb_clock_tick_advances_counter();
void test_generate_clock_tick_advances_counter();
void test_handle_sysex_drops_oversize();
void test_config_manager_wipes_legacy_slot_stride();
void test_slot_lfo_lanes_round_trip_through_slot_storage();
void test_schema6_slot_migration_preserves_downstream_profile_bytes();
void test_schema6_direct_migration_preserves_profiles_macro_and_scenes();
void test_profile_modulation_round_trip_preserves_arg_and_lfo_lanes();
void test_schema7_migration_relocates_macro_and_scene_tail();
void test_config_mutation_during_stream_stays_valid();
void test_seedbox_link_begin_sends_hello_and_identity_ping();
void test_seedbox_link_hello_triggers_ack();
void test_seedbox_link_keepalive_and_timeout_restart_handshake();
void test_clock_start_stop_flags();
void test_clock_tick_stream_counts_cleanly();
void test_clock_ppqn_start_stop_continue();
void test_clock_ppqn_timing_accuracy_with_tempo_jump();
#endif

void setup() {
    UNITY_BEGIN();
    RUN_TEST(test_scoped_analog_provider_nesting);
    RUN_TEST(test_sequence_provider_cycles_values);
    RUN_TEST(test_set_provider_returns_previous);
    RUN_TEST(test_digital_provider_overrides_matrix_reads);
    RUN_TEST(test_parse_basic_sysex_template);
    RUN_TEST(test_parse_14bit_sysex_template);
    RUN_TEST(test_parse_rejects_bad_template);
    RUN_TEST(test_sysex_template_config_mutation_stays_valid);
    RUN_TEST(test_bulk_config_assembler_handles_chunks);
    RUN_TEST(test_bulk_config_assembler_waits_for_balanced_frame);
    RUN_TEST(test_bulk_config_assembler_resyncs_on_wrapper_start);
    RUN_TEST(test_bulk_config_assembler_detects_overflow);
    RUN_TEST(test_bulk_config_assembler_rejects_orphaned_fragment);
    RUN_TEST(test_bulk_config_assembler_updates_sequence_hint_after_restart);
    RUN_TEST(test_bulk_config_assembler_expires_abandoned_frame);
    RUN_TEST(test_format_ack_includes_checksum_and_seq);
    RUN_TEST(test_device_schema_advertises_runtime_controls);
    RUN_TEST(test_bulk_config_accepts_numeric_slot_type);
    RUN_TEST(test_bulk_config_accepts_wider_numeric_slot_type);
    RUN_TEST(test_bulk_config_accepts_integral_float_slot_type);
    RUN_TEST(test_bulk_config_accepts_type_name_alias);
    RUN_TEST(test_debounce_reports_state_change_after_stable_interval);
    RUN_TEST(test_debounce_restarts_timer_when_signal_bounces);
    RUN_TEST(test_exponential_moving_average_clamps_alpha_bounds);
    RUN_TEST(test_exponential_moving_average_rounds_weighted_result);
    RUN_TEST(test_arg_sanitize_clamps_sources);
    RUN_TEST(test_compute_slot_arg_level_blends_followers);
    RUN_TEST(test_legacy_arg_migration_populates_slots);
    RUN_TEST(test_led_animator_cycles_mode_order);
    RUN_TEST(test_led_animator_invalid_mode_falls_back_to_static);
    RUN_TEST(test_led_manager_clamps_brightness_to_board_power_profile);
    RUN_TEST(test_display_owner_od01_startup_dominates);
    RUN_TEST(test_display_owner_od02_config_modal_dominates_status);
    RUN_TEST(test_display_owner_od03_lfo_modal_dominates_status);
    RUN_TEST(test_display_owner_od04_jitter_modal_dominates_status);
    RUN_TEST(test_display_owner_od05_diagnostics_modal_dominates_status);
    RUN_TEST(test_display_owner_od06_status_dominates_non_modal);
    RUN_TEST(test_display_owner_od07_control_follows_status_timeout);
    RUN_TEST(test_display_owner_od08_screensaver_only_when_idle);
    RUN_TEST(test_diagnostic_record_persists_boot_and_apply_events);
    RUN_TEST(test_diagnostic_record_rejects_corrupt_storage);
    RUN_TEST(test_diagnostic_record_loop_overrun_only_grows);
    RUN_TEST(test_command_queue_preserves_existing_frame_on_overflow);
    RUN_TEST(test_command_queue_ingests_newline_terminated_input);
    RUN_TEST(test_command_queue_ignores_carriage_returns);
    RUN_TEST(test_command_queue_discards_overlong_input_until_newline);
    RUN_TEST(test_command_queue_initialize_clears_stale_dmame_state);
    RUN_TEST(test_command_queue_dequeue_sanitizes_invalid_dmame_state);
    RUN_TEST(test_scheduler_initializes_recurring_task_layout);
    RUN_TEST(test_runtime_pending_note_off_fires_when_due);
    RUN_TEST(test_runtime_pending_note_off_overflow_tracks_drop);
    RUN_TEST(test_runtime_note_admission_drops_note_when_release_queue_is_full);
    RUN_TEST(test_runtime_modulation_transport_budget_spreads_42_slot_burst);
    RUN_TEST(test_runtime_modulated_note_stress_preserves_note_off_capacity);
    RUN_TEST(test_runtime_sustained_cc_modulation_coalesces_and_remains_fair);
    RUN_TEST(test_runtime_mixed_modulation_admission_reaches_every_slot);
    RUN_TEST(test_runtime_failed_modulated_note_retries_after_release_capacity_returns);
    RUN_TEST(test_runtime_diagnostics_log_only_on_counter_changes);
    RUN_TEST(test_process_midi_polls_usb_clock_without_timer_isr_gate);
    RUN_TEST(test_internal_clock_ticks_continue_without_timeout_gap);
    RUN_TEST(test_internal_clock_catchup_is_phase_preserving_and_bounded);
    RUN_TEST(test_clocked_feed_emits_non_arp_slots_while_arp_runs);
    RUN_TEST(test_clocked_feed_ignores_unconfigured_default_slots);
    RUN_TEST(test_display_no_ack_suppresses_runtime_retry);
    RUN_TEST(test_webserial_state_snapshot_emits_expected_json);
    RUN_TEST(test_webserial_slot_patch_emits_schema_and_legacy_payloads);
    RUN_TEST(test_ui_update_note_dynamics_maps_control_pots);
    RUN_TEST(test_ui_update_arp_tuning_updates_length_and_shape);
    RUN_TEST(test_ui_update_arp_tuning_edit_mode_updates_gate_and_octave);
    RUN_TEST(test_ui_update_filter_tuning_persists_slot_payload);
    RUN_TEST(test_ui_filter_tuning_remote_payload_blocks_mismatched_control_pots);
    RUN_TEST(test_ui_filter_tuning_remote_payload_cancels_pending_local_persist);
    RUN_TEST(test_ui_stream_webserial_state_uses_active_slot_context);
    RUN_TEST(test_wait_guard_clamps_when_threshold_exceeds_wait);
    RUN_TEST(test_wait_guard_preserves_positive_delta);
    RUN_TEST(test_waveform_ranges);
    RUN_TEST(test_phase_continuity_free_run);
    RUN_TEST(test_sync_ticks_at_120_bpm);
    RUN_TEST(test_div_mult_math);
    RUN_TEST(test_sample_hold_length);
    RUN_TEST(test_golden_stats);
    RUN_TEST(test_lfo_clock_consumes_ticks);
    RUN_TEST(test_lfo_apply_profile_resets_sync_timing_baseline);
    RUN_TEST(test_lfo_slot_value_route_emits_slot_callback);
    RUN_TEST(test_lfo_slot_value_route_applies_signed_amount_and_range);
    RUN_TEST(test_slot_modulation_composes_ef_then_lfos);
    RUN_TEST(test_slot_modulation_supports_lfo_without_ef);
    RUN_TEST(test_slot_modulation_clamps_after_each_lane);
    RUN_TEST(test_slot_modulation_honors_ef_replace_before_lfo);
    RUN_TEST(test_slot_modulation_applies_replace_and_scale_lane_modes);
    RUN_TEST(test_slot_modulation_distinguishes_unipolar_add_from_centered);
    RUN_TEST(test_slot_modulation_centered_full_amount_spans_midi_range);
    RUN_TEST(test_slot_modulation_legacy_replace_preserves_output_curve);
    RUN_TEST(test_peak_mode_rises_and_falls);
    RUN_TEST(test_rms_mode_converges);
    RUN_TEST(test_gate_mode_hysteresis);
    RUN_TEST(test_idle_floor_suppresses_disconnected_float);
    RUN_TEST(test_auto_baseline_converges);
    RUN_TEST(test_auto_gain_targets_level);
    RUN_TEST(test_stats_report_mode_and_value);
    RUN_TEST(test_envelope_stats_sine_trace);
    RUN_TEST(test_envelope_stats_step_trace);
    RUN_TEST(test_envelope_stats_idle_noise);
    RUN_TEST(test_no_heap_growth_over_fake_runtime);
    RUN_TEST(test_start_stop_cycle);
    RUN_TEST(test_pot_root_drives_default);
    RUN_TEST(test_note_dynamics_shape_arp_note_velocity_and_probability);
    RUN_TEST(test_slot_root_wins_over_pot);
    RUN_TEST(test_external_callback_sets_root);
    RUN_TEST(test_external_base_note_without_callback);
    RUN_TEST(test_external_missing_inputs_falls_back_to_pot);
    RUN_TEST(test_catches_up_when_ticks_pile_up);
    RUN_TEST(test_large_tick_backlog_is_bounded_and_not_replayed);
    RUN_TEST(test_random_shape_respects_jitter_depth);
    RUN_TEST(test_updown_shape_walks_full_range);
    RUN_TEST(test_drunk_shape_is_deterministic);
    RUN_TEST(test_drunk_shape_jitter_depth_expands_walk);
    RUN_TEST(test_euclidean_advances_pitch_by_hit_not_rest_position);
    RUN_TEST(test_swing_delays_offbeat_notes);
    RUN_TEST(test_stop_cancels_delayed_note_on);
    RUN_TEST(test_tempo_change_updates_tick_ms);
    RUN_TEST(test_profile_crc_rejects_corruption);
    RUN_TEST(test_profile_bounds_clamp);
    RUN_TEST(test_profile_round_trip_preserves_profile_payload);
    RUN_TEST(test_profile_v5_migration_preserves_state_and_defaults_pattern_length);
    RUN_TEST(test_config_load_prefers_primary_when_backup_copy_is_invalid);
    RUN_TEST(test_config_load_restores_from_backup_and_repairs_primary);
    RUN_TEST(test_config_load_restores_from_backup_when_primary_crc_is_invalid);
    RUN_TEST(test_config_load_resets_to_defaults_when_primary_and_backup_are_both_corrupt);
    RUN_TEST(test_profile_save_interruption_leaves_latest_copy_in_backup);
    RUN_TEST(test_lowpass_highpass_response);
    RUN_TEST(test_system_report);
    RUN_TEST(test_dispatch_handles_known_command);
    RUN_TEST(test_dispatch_handles_documented_query_commands);
    RUN_TEST(test_dispatch_set_led_clamps_without_persisting);
    RUN_TEST(test_dispatch_abort_set_all_clears_incomplete_upload);
    RUN_TEST(test_applied_checksum_covers_exported_filter_led_and_baseline_state);
    RUN_TEST(test_applied_checksum_covers_slot_arg_and_lfo_modulation);
    RUN_TEST(test_dispatch_handles_enter_config_mode_command);
    RUN_TEST(test_dispatch_handles_live_slot_injection_command);
    RUN_TEST(test_dispatch_handles_midi_test_command);
    RUN_TEST(test_dispatch_handles_live_note_dynamics_command_without_boot_request);
    RUN_TEST(test_dispatch_handles_live_arp_runtime_commands);
    RUN_TEST(test_dispatch_get_mod_matrix_reports_routes_and_conflicts);
    RUN_TEST(test_dispatch_get_mod_matrix_reports_lfo_route_truncation);
    RUN_TEST(test_dispatch_handles_profile_save_load_reset_commands);
    RUN_TEST(test_dispatch_reassembles_chunked_profile_patch);
    RUN_TEST(test_dispatch_active_profile_lfo_patch_applies_live);
    RUN_TEST(test_restore_active_profile_runtime_rehydrates_saved_modulation_snapshot);
    RUN_TEST(test_dispatch_set_arp_updates_live_state_without_persisting);
    RUN_TEST(test_dispatch_set_profile_arp_pattern_length_applies_and_persists);
    RUN_TEST(test_dispatch_set_clock_updates_live_state_without_persisting);
    RUN_TEST(test_dispatch_set_jitter_updates_live_state_without_persisting);
    RUN_TEST(test_dispatch_set_note_dynamics_updates_live_state_without_persisting);
    RUN_TEST(test_dispatch_inactive_profile_patch_merges_with_stored_profile_snapshot);
    RUN_TEST(test_dispatch_profile_patch_normalizes_route_scalars);
    RUN_TEST(test_dispatch_profile_patch_rejects_invalid_route_fields);
    RUN_TEST(test_dispatch_handles_macro_and_scene_snapshot_commands);
    RUN_TEST(test_dispatch_rejects_unknown_command);
    RUN_TEST(test_dispatch_set_all_reports_negative_contract_errors);
    RUN_TEST(test_display_init_failure_leaves_protocol_responsive);
    RUN_TEST(test_profile_storage_commands_restore_and_reset_live_state);
    RUN_TEST(test_macro_and_scene_storage_commands_report_inventory_and_restore_state);
#if defined(UNIT_TEST) && defined(USB_MIDI_STUB)
    RUN_TEST(test_program_change);
    RUN_TEST(test_aftertouch);
    RUN_TEST(test_mod_wheel);
    RUN_TEST(test_pot_burst_keeps_cc_counters_honest);
    RUN_TEST(test_pitch_bend);
    RUN_TEST(test_send_nrpn);
    RUN_TEST(test_receive_nrpn);
    RUN_TEST(test_parameter_decoders_are_isolated_per_channel);
    RUN_TEST(test_send_sysex);
    RUN_TEST(test_oversized_sysex_is_rejected);
    RUN_TEST(test_drop_unsupported_usb_type);
    RUN_TEST(test_handle_sysex_drops_oversize);
    RUN_TEST(test_usb_clock_tick_advances_counter);
    RUN_TEST(test_generate_clock_tick_advances_counter);
    RUN_TEST(test_clock_start_stop_flags);
    RUN_TEST(test_clock_tick_stream_counts_cleanly);
    RUN_TEST(test_clock_ppqn_start_stop_continue);
    RUN_TEST(test_clock_ppqn_timing_accuracy_with_tempo_jump);
    RUN_TEST(test_config_manager_wipes_legacy_slot_stride);
    RUN_TEST(test_slot_lfo_lanes_round_trip_through_slot_storage);
    RUN_TEST(test_schema6_slot_migration_preserves_downstream_profile_bytes);
    RUN_TEST(test_schema6_direct_migration_preserves_profiles_macro_and_scenes);
    RUN_TEST(test_profile_modulation_round_trip_preserves_arg_and_lfo_lanes);
    RUN_TEST(test_schema7_migration_relocates_macro_and_scene_tail);
    RUN_TEST(test_config_mutation_during_stream_stays_valid);
    RUN_TEST(test_seedbox_link_begin_sends_hello_and_identity_ping);
    RUN_TEST(test_seedbox_link_hello_triggers_ack);
    RUN_TEST(test_seedbox_link_keepalive_and_timeout_restart_handshake);
#endif
    UNITY_END();
}

void loop() {}

// Unity's per-test hooks keep IO providers from bleeding between test files.
void setUp() {
    hardware::resetAnalogReadProvider();
    hardware::resetDigitalReadProvider();
}

void tearDown() {
    hardware::resetAnalogReadProvider();
    hardware::resetDigitalReadProvider();
}
