#!/usr/bin/env python3
"""Generate firmware OLED help and a quick reference from the control registry."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


HEADER_PREAMBLE = """// Generated by tools/generate_control_artifacts.py. Do not edit by hand.
#ifndef CONTROL_HELP_GENERATED_H
#define CONTROL_HELP_GENERATED_H

#include <stddef.h>
#include <stdint.h>

struct ControlHelpEntry {
    uint8_t mask;
    const char *line1;
    const char *line2;
    const char *line3;
};

constexpr ControlHelpEntry kControlHelpEntries[] = {
"""


def control_mask(buttons: list[int]) -> int:
    mask = 0
    for button in buttons:
        if button < 0 or button > 5:
            raise ValueError(f"control button index out of range: {button}")
        mask |= 1 << button
    return mask


def cpp_string(value: str) -> str:
    return json.dumps(value)


def render_header(registry: dict) -> str:
    lines = [HEADER_PREAMBLE]
    seen: set[int] = set()
    for context in registry["contexts"]:
        mask = control_mask(context["mask"])
        if mask in seen:
            raise ValueError(f"duplicate contextual help mask: {mask}")
        seen.add(mask)
        display_lines = [context[key] for key in ("line1", "line2", "line3")]
        for display_line in display_lines:
            if len(display_line) > 21:
                raise ValueError(f"OLED help line exceeds 21 characters: {display_line!r}")
        lines.append(
            f"    {{{mask}, {cpp_string(display_lines[0])}, {cpp_string(display_lines[1])}, "
            f"{cpp_string(display_lines[2])}}},\n"
        )
    lines.append("};\n\n")
    lines.append(
        "constexpr size_t kControlHelpEntryCount = "
        "sizeof(kControlHelpEntries) / sizeof(kControlHelpEntries[0]);\n\n"
    )
    lines.append("#endif // CONTROL_HELP_GENERATED_H\n")
    return "".join(lines)


def render_quick_reference(registry: dict) -> str:
    lines = [
        "<!-- Generated by tools/generate_control_artifacts.py. Do not edit by hand. -->\n",
        "# On-Device Control Quick Reference\n\n",
        "## Control Namespaces\n\n",
        "| Control | Family | Immediate action | Layer |\n",
        "| --- | --- | --- | --- |\n",
    ]
    for item in registry["namespaces"]:
        lines.append(
            f"| Ctrl{item['button']} | {item['family']} | {item['short']} | {item['layer']} |\n"
        )
    lines.extend(
        [
            "\n## Gestures\n\n",
            "| Gesture | Action | Layer | Family | Reversible |\n",
            "| --- | --- | --- | --- | --- |\n",
        ]
    )
    for item in registry["combos"]:
        lines.append(
            f"| `{item['control']}` | {item['label']} | {item['layer']} | "
            f"{item['family']} | {'Yes' if item['reversible'] else 'No'} |\n"
        )
    return "".join(lines)


def write_or_check(path: Path, content: str, check: bool) -> bool:
    if check:
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            print(f"stale generated control artifact: {path}")
            return False
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"wrote {path}")
    return True


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", default=".", help="Repository root")
    parser.add_argument("--check", action="store_true", help="Fail if generated files are stale")
    args = parser.parse_args()

    root = Path(args.root).resolve()
    registry_path = root / "docs/reference/on_device_control_registry.json"
    registry = json.loads(registry_path.read_text(encoding="utf-8"))
    if registry.get("schema_version") != 2:
        raise SystemExit("unsupported on-device control registry schema")

    outputs = (
        (root / "firmware/include/generated/ControlHelp.generated.h", render_header(registry)),
        (
            root / "docs/reference/generated/OnDeviceQuickReference.md",
            render_quick_reference(registry),
        ),
    )
    if not all(write_or_check(path, content, args.check) for path, content in outputs):
        raise SystemExit(1)


if __name__ == "__main__":
    main()
