#!/usr/bin/env python3
"""Generate MN42 host and firmware artifacts from machine-readable contract sources."""

from __future__ import annotations

import argparse
import copy
import json
import pathlib
import sys


CONTRACT_PATH = pathlib.Path("interop/mn42_contract.json")


def load_sources(root: pathlib.Path) -> tuple[dict, dict]:
    contract = json.loads((root / CONTRACT_PATH).read_text(encoding="utf-8"))
    schema = json.loads((root / contract["schema_source"]).read_text(encoding="utf-8"))
    manifest = contract["manifest"]
    if schema.get("schema_version") != manifest.get("schema_version"):
        raise ValueError("canonical schema_version does not match manifest schema_version")
    slots = schema.get("properties", {}).get("slots", {})
    if {slots.get("minItems"), slots.get("maxItems")} != {manifest.get("slot_count")}:
        raise ValueError("canonical slot schema does not match manifest slot_count")
    ef_slots = schema.get("properties", {}).get("efSlots", {})
    if {ef_slots.get("minItems"), ef_slots.get("maxItems")} != {manifest.get("envelope_count")}:
        raise ValueError("canonical EF schema does not match manifest envelope_count")
    return contract, schema


def render_app_manifest(contract: dict) -> str:
    manifest = contract["manifest"]
    constants = (
        ("MN42_DEVICE_NAME", "device_name"),
        ("MN42_SCHEMA_VERSION", "schema_version"),
        ("MN42_SLOT_COUNT", "slot_count"),
        ("MN42_POT_COUNT", "pot_count"),
        ("MN42_ENVELOPE_COUNT", "envelope_count"),
        ("MN42_LED_COUNT", "led_count"),
        ("MN42_POWER_PROFILE", "power_profile"),
        ("MN42_LED_BRIGHTNESS_CAP", "led_brightness_cap"),
        ("MN42_RAIL_TOPOLOGY_VERIFIED", "rail_topology_verified"),
    )
    lines = ["// Generated by tools/generate_contract_artifacts.py. Do not edit directly."]
    for js_name, key in constants:
        lines.append(f"export const {js_name} = {json.dumps(manifest[key])};")
    capabilities = json.dumps(contract["app_capability_defaults"], indent=2)
    lines.extend([
        "",
        f"const DEFAULT_CAPABILITIES = {capabilities};",
        "",
        "// Build the browser's fallback manifest so the UI still knows slot counts,",
        "// schema version, and capability defaults before a real device handshakes.",
        "export function createLocalManifest({ uiVersion, argMethodCount, capabilities } = {}) {",
        "  return {",
        "    ui_version: uiVersion,",
        "    device_name: MN42_DEVICE_NAME,",
        "    schema_version: MN42_SCHEMA_VERSION,",
        "    slot_count: MN42_SLOT_COUNT,",
        "    pot_count: MN42_POT_COUNT,",
        "    envelope_count: MN42_ENVELOPE_COUNT,",
        "    arg_method_count: argMethodCount,",
        "    led_count: MN42_LED_COUNT,",
        "    power_profile: MN42_POWER_PROFILE,",
        "    led_brightness_cap: MN42_LED_BRIGHTNESS_CAP,",
        "    rail_topology_verified: MN42_RAIL_TOPOLOGY_VERIFIED,",
        "    capabilities: {",
        "      ...DEFAULT_CAPABILITIES,",
        "      ...(capabilities && typeof capabilities === 'object' ? capabilities : {})",
        "    }",
        "  };",
        "}",
        "",
    ])
    return "\n".join(lines)


def render_bridge_manifest(contract: dict) -> str:
    manifest = json.dumps(contract["manifest"], indent=2)
    return (
        "// Generated by tools/generate_contract_artifacts.py. Do not edit directly.\n"
        f"const MN42_MANIFEST_CONTRACT = Object.freeze({manifest});\n\n"
        "module.exports = {\n  MN42_MANIFEST_CONTRACT,\n};\n"
    )


def render_firmware_manifest(contract: dict) -> str:
    manifest = contract["manifest"]
    verified = "true" if manifest["rail_topology_verified"] else "false"
    return f"""// Generated by tools/generate_contract_artifacts.py. Do not edit directly.
#ifndef MANIFEST_CONTRACT_H
#define MANIFEST_CONTRACT_H

#include <cstdint>

namespace ManifestContract {{
inline constexpr char kDeviceName[] = {json.dumps(manifest['device_name'])};
inline constexpr uint16_t kSchemaVersion = {manifest['schema_version']};
inline constexpr uint8_t kSlotCount = {manifest['slot_count']};
inline constexpr uint8_t kPotCount = {manifest['pot_count']};
inline constexpr uint8_t kEnvelopeCount = {manifest['envelope_count']};
inline constexpr uint8_t kDefaultLedCount = {manifest['led_count']};
inline constexpr char kDefaultPowerProfile[] = {json.dumps(manifest['power_profile'])};
inline constexpr uint8_t kDefaultLedBrightnessCap = {manifest['led_brightness_cap']};
inline constexpr bool kDefaultRailTopologyVerified = {verified};
}} // namespace ManifestContract

#endif // MANIFEST_CONTRACT_H
"""


def render_firmware_schema(contract: dict, app_schema: dict) -> str:
    device_schema = copy.deepcopy(app_schema)
    for key in contract["device_schema"].get("exclude_properties", []):
        device_schema.get("properties", {}).pop(key, None)
    device_schema["x_mn42"] = contract["device_schema"]["authority"]
    encoded = json.dumps(device_schema, separators=(",", ":"), ensure_ascii=False)
    delimiter = "MN42_SCHEMA"
    if f"){delimiter}\"" in encoded:
        raise ValueError("firmware schema collides with raw-string delimiter")
    return f"""// Generated by tools/generate_contract_artifacts.py. Do not edit directly.
#ifndef GENERATED_CONFIG_SCHEMA_H
#define GENERATED_CONFIG_SCHEMA_H

namespace ManifestContract {{
static const char kConfigSchemaJson[] PROGMEM = R\"{delimiter}({encoded}){delimiter}\";
}} // namespace ManifestContract

#endif // GENERATED_CONFIG_SCHEMA_H
"""


def expected_artifacts(root: pathlib.Path) -> dict[pathlib.Path, str]:
    contract, schema = load_sources(root)
    return {
        root / "App/manifest_contract.js": render_app_manifest(contract),
        root / "bridge/lib/manifest_contract.js": render_bridge_manifest(contract),
        root / "firmware/include/protocol/ManifestContract.h": render_firmware_manifest(contract),
        root / "firmware/include/protocol/GeneratedConfigSchema.h": render_firmware_schema(contract, schema),
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", default=".", help="Repository root")
    parser.add_argument("--check", action="store_true", help="Fail when generated artifacts are stale")
    args = parser.parse_args()
    root = pathlib.Path(args.root).resolve()
    stale: list[str] = []
    for path, expected in expected_artifacts(root).items():
        if args.check:
            actual = path.read_text(encoding="utf-8") if path.exists() else None
            if actual != expected:
                stale.append(str(path.relative_to(root)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected, encoding="utf-8")
    if stale:
        print("generated contract artifacts are stale:", file=sys.stderr)
        for path in stale:
            print(f"  - {path}", file=sys.stderr)
        print("run: python3 tools/generate_contract_artifacts.py --root .", file=sys.stderr)
        raise SystemExit(1)
    print("contract artifacts are current" if args.check else "generated contract artifacts")


if __name__ == "__main__":
    main()
